#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10 

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Autostart terminal for workspace 2
bspc rule -a Alacritty -o desktop='^1' state=tiled follow=on

# Autostart browser for workspace 1
bspc rule -a Google-chrome -o desktop='^2' state=tiled follow=off

google-chrome-stable &
sleep 1
alacritty &

feh --bg-fill $HOME/Downloads/blue-sky/wallpapers/blue3.png

xsetroot -cursor_name left_ptr &
~/.config/polybar/./launch.sh

picom &

